import chalk from 'chalk';
import ora from 'ora';
import { readFile } from 'node:fs/promises';
import { ConfigManager } from '../cli/ConfigManager.js';
import { gitExposure, openVault, writePrivateFile } from '../cli/vault.js';
import { parseDotenv, serializeEnvLine, validateSecretName } from '../format/dotenv.js';

/**
 * Inject decrypted secrets into an env file (merged with any existing values).
 */
export async function injectCommand(options: {
  env: string;
  file?: string;
  force?: boolean;
}): Promise<void> {
  const configManager = new ConfigManager();

  if (!(await configManager.exists())) {
    console.log(chalk.red('❌ SecretForge not initialized. Run `sf init` first.'));
    return;
  }

  if (!options.env) {
    console.log(chalk.red('❌ Environment is required. Use --env <environment>'));
    return;
  }

  const outputFile = options.file || `.env.${options.env}`;

  // Refuse to write plaintext secrets into a file git is tracking.
  const exposure = gitExposure(outputFile);
  if (exposure === 'tracked' && !options.force) {
    throw new Error(
      `${outputFile} is tracked by git. Writing secrets into it would commit them. ` +
        `Untrack it (git rm --cached "${outputFile}") or pass --force.`
    );
  }

  const config = await configManager.load();
  const spinner = ora('Injecting secrets...').start();
  const storage = openVault(configManager, config);

  try {
    const secrets = await storage.listSecrets({
      project: config.project,
      environment: options.env,
    });

    if (secrets.length === 0) {
      spinner.warn(`No secrets found for environment: ${options.env}`);
      return;
    }

    let existingContent = '';
    try {
      existingContent = await readFile(outputFile, 'utf-8');
    } catch {
      // File doesn't exist yet
    }

    const vars = parseDotenv(existingContent);
    const skipped: string[] = [];
    for (const secret of secrets) {
      if (validateSecretName(secret.name) !== true) {
        skipped.push(secret.name);
        continue;
      }
      vars.set(secret.name, await storage.decryptSecret(secret));
    }

    const lines: string[] = [
      `# Generated by SecretForge - ${new Date().toISOString()}`,
      `# Environment: ${options.env}`,
      '',
    ];
    for (const [key, value] of vars.entries()) {
      if (validateSecretName(key) !== true) continue;
      lines.push(serializeEnvLine(key, value));
    }

    await writePrivateFile(outputFile, lines.join('\n') + '\n');
    spinner.succeed(`Secrets injected into ${outputFile} (mode 600)`);

    console.log(chalk.bold('\n📋 Injected Secrets:'));
    secrets
      .filter((s) => !skipped.includes(s.name))
      .forEach((secret) => console.log(chalk.gray(`  • ${secret.name}`)));

    if (skipped.length > 0) {
      console.log(
        chalk.yellow(
          `\n⚠️  Skipped ${skipped.length} secret(s) with names that are not valid/safe env vars: ${skipped.join(', ')}`
        )
      );
    }

    if (exposure === 'untracked-not-ignored') {
      console.log(
        chalk.red(`\n🚨 ${outputFile} is NOT git-ignored. Add it to .gitignore before your next commit.`)
      );
    }
  } catch (error) {
    spinner.fail('Failed to inject secrets');
    throw error;
  } finally {
    storage.close();
  }
}
